apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: "[\n  {\n    \"apiVersion\": \"infinispan.org/v1\",\n    \"kind\"\
      : \"Infinispan\",\n    \"metadata\": {\n      \"name\": \"example-infinispan\"\
      \n    },\n    \"spec\": {\n      \"replicas\": 1\n    }\n  },\n  {\n    \"apiVersion\"\
      : \"infinispan.org/v2alpha1\",\n    \"kind\": \"Cache\",\n    \"metadata\"\
      : {\n      \"name\": \"example-cache\"\n    },\n    \"spec\": {\n      \"adminAuth\"\
      : {\n        \"secretName\": \"basic-auth\"\n      },\n      \"clusterName\"\
      : \"example-infinispan\",\n      \"name\": \"mycache\"\n    }\n  }\n]\n"
    capabilities: Full Lifecycle
    categories: Database
    certified: 'false'
    containerImage: registry.redhat.io/datagrid/datagrid-8-rhel8-operator@sha256:689ffc87e2334c132b1ef68b692e2f8a2829596b4037fa11211b585ff0945ab7
    createdAt: '2020-10-06T20:33:23Z'
    description: Create and manage Red Hat Data Grid clusters.
    operators.openshift.io/infrastructure-features: '["Disconnected"]'
    repository: https://github.com/infinispan/infinispan-operator
    support: Red Hat
    tectonic-visibility: ocs
  name: datagrid-operator.v8.1.1
  namespace: placeholder
spec:
  customresourcedefinitions:
    owned:
    - description: Cache is the Schema for the caches API
      displayName: Infinispan Cache
      kind: Cache
      name: caches.infinispan.org
      version: v2alpha1
    - description: An Infinispan cluster instance.
      displayName: Infinispan Cluster
      kind: Infinispan
      name: infinispans.infinispan.org
      resources:
      - kind: ConfigMap
        version: v1
      - kind: Secret
        version: v1
      - kind: Service
        version: v1
      - kind: Pod
        version: v1
      specDescriptors:
      - description: Sets the number of nodes in the cluster.
        displayName: Replicas
        path: replicas
      - description: Sets an image to bootstrap the Infinispan nodes.
        displayName: Image
        path: image
      - description: Sets the CPU limits for each Infinispan node.
        displayName: CPU
        path: container.cpu
      - description: Sets the memory limits for each Infinispan node.
        displayName: Memory
        path: container.memory
      - description: Appends JVM options to each Infinispan node.
        displayName: Extra JVM Options
        path: container.extraJvmOpts
      - description: Name of the secrect that contains auth info.
        displayName: Endpoint Secret Name
        path: security.endpointSecretName
      - description: Select how encryption certificates are provided [Secret,Service].
        displayName: Endpoint Encryption Type
        path: security.endpointEncryption.type
      - description: Platform service that serves certificates (openshift.io/service-cert
          is supported).
        displayName: Serving Certs Service Name
        path: security.endpointEncryption.certServiceName
      - description: Name of the secrect that contains certificates.
        displayName: Certificates Secret Name
        path: security.endpointEncryption.certSecretName
      - description: Select service type provided [Cache,DataGrid].
        displayName: Service Type
        path: service.type
      - description: Local Infinispan node storage capacity (DataGrid service only).
        displayName: Local Storage Capacity
        path: service.container.storage
      - description: Name of local site (DataGrid service only).
        displayName: Name Of Local Site
        path: service.sites.local.name
      - description: Kubernetes service type for cross-site communications [LoadBalancer,NodePort]
          (DataGrid service only).
        displayName: Kubernetes Service Type For Cross-Site Network
        path: service.sites.local.expose.type
      - description: Name of one of the sites (DataGrid service only)
        displayName: Name Of Site
        path: service.sites.locations[0].name
      - description: Site URL for communicating with site (DataGrid service only).
          Prefixed with minikube:// for Minikube sites, and openshift:// for OpenShift
          sites.
        displayName: Site URL
        path: service.sites.locations[0].url
      - description: Secret name containing credentials to talk to site (DataGrid
          service only).
        displayName: Secret For Site
        path: service.sites.locations[0].secretName
      - description: Defines logging categories and log levels.
        displayName: Logging Categories
        path: logging.categories
      - description: Externally exposed Kubernetes service type.
        displayName: Exposed Kubernetes Service Type
        path: expose.type
      statusDescriptors:
      - description: Type of condition.
        displayName: Condition Type
        path: conditions[0].type
      - description: Status of condition.
        displayName: Condition Status
        path: conditions[0].status
      - description: Message of condition.
        displayName: Condition Message
        path: conditions[0].message
      version: v1
  description: 'Red Hat Data Grid is a distributed, in-memory data store that increases
    application performance and delivers open-source capabilites to handle demanding
    use cases.


    ### Core Capabilities

    * **Schemaless data structure:** Store different objects as key-value pairs.

    * **Grid-based data storage:** Distribute and replicate data across clusters.

    * **Elastic scaling:** Dynamically adjust the number of nodes to meet demand without
    service disruption.

    * **Data interoperability:** Store, retrieve, and query data in the grid from
    different endpoints.

    * **High availability:** Always have access to your data.


    ### Red Hat Data Grid Operator Features

    * Operational intelligence that simplifies Red Hat Data Grid cluster deployment.

    * REST and Hot Rod endpoints available at port `11222`.

    * Cache service for a high-performance, ephemeral data store.

    * Data Grid service for a fully configurable Red Hat Data Grid cluster.

    * Default application user: `developer`. Red Hat Data Grid Operator generates
    credentials in an authentication secret at startup.

    * Red Hat Data Grid pods request `0.25` (limit `0.50`) CPUs, 512MiB of memory
    and 1Gi of ReadWriteOnce persistent storage. Red Hat Data Grid Operator lets you
    adjust resource allocation to suit your requirements.

    '
  displayName: Data Grid
  icon:
  - base64data: PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAxMDAgMTAwIj48ZGVmcz48c3R5bGU+LmNscy0xe2ZpbGw6I2Q3MWUwMDt9LmNscy0ye2ZpbGw6I2MyMWEwMDt9LmNscy0ze2ZpbGw6I2VhZWFlYTt9LmNscy00e2ZpbGw6I2ZmZjt9LmNscy01e2ZpbGw6I2I3YjdiNzt9PC9zdHlsZT48L2RlZnM+PHRpdGxlPnByb2R1Y3RpY29uc18xMDE3X1JHQl9EYXRhR3JpZCBmaW5hbCBjb2xvcjwvdGl0bGU+PGcgaWQ9IkxheWVyXzEiIGRhdGEtbmFtZT0iTGF5ZXIgMSI+PGNpcmNsZSBjbGFzcz0iY2xzLTEiIGN4PSI1MCIgY3k9IjUwIiByPSI1MCIgdHJhbnNmb3JtPSJ0cmFuc2xhdGUoLTIwLjcxIDUwKSByb3RhdGUoLTQ1KSIvPjxwYXRoIGNsYXNzPSJjbHMtMiIgZD0iTTg1LjM2LDE0LjY0QTUwLDUwLDAsMCwxLDE0LjY0LDg1LjM2WiIvPjxwYXRoIGNsYXNzPSJjbHMtMyIgZD0iTTc0LjUzLDU2Ljc1QzU0LjI2LDU2LDUzLjgzLDc2LjUxLDMyLjgsNzQuMzgsMjIsNzMuMjksMTQsNjEuOSwxNi4xNyw1NC41OGw2LTE4LjU4Yy0uOTQsOC42LDEyLjM0LDIyLjU2LDIzLjExLDIzLjY1LDEyLjUyLDEuMjcsMTUuNTctNC4yOCwyOS4yLTIuOSIvPjxwYXRoIGNsYXNzPSJjbHMtNCIgZD0iTTgwLjQ3LDM5LjIxQzY5LjQ3LDM4LjEsNjEuNzksNDkuMzQsNTQsNTkuNDJjNi4zNS0xLjA2LDEwLjY3LTMuNjYsMjAuNS0yLjY3aC4wNmM0Ljc2LjQ4LDQuOTUsMy41Nyw0LjczLDVsNi40Ni0xOEM4Niw0Mi4yOSw4NSwzOS42Nyw4MC40NywzOS4yMVoiLz48cGF0aCBjbGFzcz0iY2xzLTUiIGQ9Ik03NC41OSw1Ni43NmgtLjA4YTIyLjM5LDIyLjM5LDAsMCwwLTE0LjM2LDQuMTYsMTcuNjEsMTcuNjEsMCwwLDAsMTAuMyw1YzMuNTIuMzYsNy43OS0xLjY4LDguODctNC4yMkM3OS41NCw2MC4zMiw3OS4zNSw1Ny4yNCw3NC41OSw1Ni43NloiLz48cGF0aCBjbGFzcz0iY2xzLTUiIGQ9Ik02OC41LDQzLjA2QzYwLjY4LDM2Ljg1LDU3LjA3LDI1LDQzLjIsMjMuNjEsMjguODUsMjIuMTYsMjMuNzksMzEuNSwyMi4yOCwzNS42N2wtLjA3LjMzYy0uMjYsMi40LjU5LDUuMjMsMi4xOCw4LjA3LDMuMjEtMS43MSw3LjU3LTIuNTcsMTMuNi0yLDguMi44MywxMi44Myw4LjE5LDE4LjE0LDE0LjUzQzYwLjA2LDUxLjUzLDY0LDQ2LjQzLDY4LjUsNDMuMDZaIi8+PC9nPjwvc3ZnPg==
    mediatype: image/svg+xml
  install:
    spec:
      clusterPermissions:
      - rules:
        - apiGroups:
          - ''
          resources:
          - nodes
          - nodes/status
          - nodes/metrics
          - nodes/spec
          - nodes/stats
          verbs:
          - get
          - list
          - watch
        - apiGroups:
          - apiextensions.k8s.io
          resources:
          - customresourcedefinitions
          - customresourcedefinitions/status
          verbs:
          - get
          - list
          - watch
        serviceAccountName: infinispan-operator
      deployments:
      - name: infinispan-operator
        spec:
          replicas: 1
          selector:
            matchLabels:
              name: infinispan-operator-alm-owned
          template:
            metadata:
              labels:
                name: infinispan-operator-alm-owned
              name: infinispan-operator-alm-owned
            spec:
              containers:
              - command:
                - infinispan-operator
                env:
                - name: WATCH_NAMESPACE
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.annotations['olm.targetNamespaces']
                - name: POD_NAME
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.name
                - name: OPERATOR_NAME
                  value: infinispan-operator
                - name: DEFAULT_IMAGE
                  value: registry.redhat.io/datagrid/datagrid-8-rhel8@sha256:054f2dee7517cc44ee6e008b9a77994d879574fb7e2f601cd08855352f459a13
                image: registry.redhat.io/datagrid/datagrid-8-rhel8-operator@sha256:689ffc87e2334c132b1ef68b692e2f8a2829596b4037fa11211b585ff0945ab7
                name: infinispan-operator
                ports:
                - containerPort: 60000
                  name: metrics
              serviceAccountName: infinispan-operator
      permissions:
      - rules:
        - apiGroups:
          - ''
          resources:
          - pods
          - services
          - endpoints
          - persistentvolumeclaims
          - events
          - configmaps
          - secrets
          verbs:
          - '*'
        - apiGroups:
          - ''
          resources:
          - pods/exec
          verbs:
          - create
        - apiGroups:
          - ''
          resources:
          - namespaces
          verbs:
          - get
        - apiGroups:
          - apps
          resources:
          - deployments
          - daemonsets
          - replicasets
          - statefulsets
          verbs:
          - '*'
        - apiGroups:
          - route.openshift.io
          resources:
          - routes
          - routes/custom-host
          verbs:
          - '*'
        - apiGroups:
          - networking.k8s.io
          resources:
          - ingresses
          verbs:
          - '*'
        - apiGroups:
          - monitoring.coreos.com
          resources:
          - servicemonitors
          verbs:
          - get
          - create
        - apiGroups:
          - infinispan.org
          resources:
          - '*'
          verbs:
          - '*'
        serviceAccountName: infinispan-operator
    strategy: deployment
  installModes:
  - supported: true
    type: OwnNamespace
  - supported: true
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: false
    type: AllNamespaces
  keywords:
  - infinispan
  - key value
  - database
  - datagrid
  - open source
  labels:
    operated-by: infinispan-operator
  links:
  - name: Blog
    url: https://developers.redhat.com/blog/category/products/accelerated-development-management/jboss-data-grid
  - name: Documentation
    url: https://access.redhat.com/documentation/en-us/red_hat_data_grid/8.1/html-single/running_data_grid_on_openshift/
  - name: Quickstart
    url: https://access.redhat.com/documentation/en-us/red_hat_data_grid/8.1/html-single/getting_started_with_data_grid_operator/
  - name: Operator Source Code
    url: https://github.com/infinispan/infinispan-operator
  - name: Product Page
    url: https://www.redhat.com/en/technologies/jboss-middleware/data-grid
  maintainers:
  - email: customerservice@redhat.com
    name: Red Hat
  maturity: alpha
  minKubeVersion: 1.11.0
  provider:
    name: Red Hat
  relatedImages:
  - image: registry.redhat.io/datagrid/datagrid-8-rhel8@sha256:054f2dee7517cc44ee6e008b9a77994d879574fb7e2f601cd08855352f459a13
    name: datagrid-8.1.1
  replaces: datagrid-operator.v8.1.0
  selector:
    matchLabels:
      operated-by: infinispan-operator
  version: 8.1.1
